#Importa todos los modulos 
from .codigopostal import CodigoPostalSerializer 
from .formapago import FormaPagoSerializer 
from .formapagodetalle import FormaPagoDetalleSerializer 
from .idioma import IdiomaSerializer 
from .incoterms import IncotermsSerializer 
from .indice import IndiceSerializer 
from .mascara import MascaraSerializer 
from .modulo import ModuloSerializer 
from .moneda import MonedaSerializer 
from .pais import PaisSerializer 
from .partido import PartidoSerializer 
from .persona import PersonaSerializer 
from .personarol import PersonaRolSerializer 
from .provincia import ProvinciaSerializer 
from .rol import RolSerializer 
from .sector import SectorSerializer 
from .tipocambio import TipoCambioSerializer 
from .tipodocumento import TipoDocumentoSerializer 
from .tipodomicilio import TipoDomicilioSerializer 
from .tipofrecuencia import TipoFrecuenciaSerializer 
from .tipoindice import TipoIndiceSerializer 
from .tiporesponsable import TipoResponsableSerializer 
from .tiposede import TipoSedeSerializer 
from .tipovalor import TipoValorSerializer 
from .unidadmedida import UnidadMedidaSerializer 
