#Importa todos los modulos 
from .codigopostal import CodigoPostalViewSet 
from .formapago import FormaPagoViewSet 
from .formapagodetalle import FormaPagoDetalleViewSet 
from .idioma import IdiomaViewSet 
from .incoterms import IncotermsViewSet 
from .indice import IndiceViewSet 
from .mascara import MascaraViewSet 
from .modulo import ModuloViewSet 
from .moneda import MonedaViewSet 
from .pais import PaisViewSet 
from .partido import PartidoViewSet 
from .persona import PersonaViewSet 
from .personarol import PersonaRolViewSet 
from .provincia import ProvinciaViewSet 
from .rol import RolViewSet 
from .sector import SectorViewSet 
from .tipocambio import TipoCambioViewSet 
from .tipodocumento import TipoDocumentoViewSet 
from .tipodomicilio import TipoDomicilioViewSet 
from .tipofrecuencia import TipoFrecuenciaViewSet 
from .tipoindice import TipoIndiceViewSet 
from .tiporesponsable import TipoResponsableViewSet 
from .tiposede import TipoSedeViewSet 
from .tipovalor import TipoValorViewSet 
from .unidadmedida import UnidadMedidaViewSet 
from .tablas import TablasViewSet
from .tablas import TablasConCodigoViewSet