# Importa todos los modulos 

from .condicioncrediticiaentidad import CondicionCrediticiaEntidadSerializer
from .contactoentidad import  ContactoEntidadSerializer
from .datosfiscalesentidad import DatosFiscalesEntidadSerializer
from .direccionentidad import DireccionEntidadSerializer
from .ejecutivoentidad import EjecutivoEntidadSerializer
from .entidad import EntidadSerializer
from .formapagoentidad import FormaPagoEntidadSerializer
from .impuestoentidad import ImpuestoEntidadSerializer
from .listaprecioentidad import ListaPrecioEntidadSerializer
from .moduloentidad import ModuloEntidadSerializer
from .sectorentidad import SectorEntidadSerializer
from .zona import ZonaSerializer
