# Generated by Django 5.1.1 on 2024-10-09 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0002_pais_codigoafip_incoterms_delete_incoterm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conceptoincluido',
            options={'verbose_name': 'Concepto Incluido', 'verbose_name_plural': 'IMPU - Conceptos Incluidos'},
        ),
        migrations.AlterModelOptions(
            name='idioma',
            options={'verbose_name': 'Idioma', 'verbose_name_plural': 'GRAL - Idioma'},
        ),
        migrations.AlterModelOptions(
            name='incoterms',
            options={'verbose_name': 'Incoterm', 'verbose_name_plural': 'GRAL - Incoterms'},
        ),
        migrations.AlterModelOptions(
            name='indice',
            options={'verbose_name': 'Indice', 'verbose_name_plural': 'GRAL - Indices'},
        ),
        migrations.AlterModelOptions(
            name='listaprecioentidad',
            options={'verbose_name': 'Listas de Precio', 'verbose_name_plural': 'ARTI - Listas de Precio por Entidad'},
        ),
        migrations.AlterModelOptions(
            name='moneda',
            options={'verbose_name': 'Moneda', 'verbose_name_plural': 'GRAL - Monedas'},
        ),
        migrations.AlterModelOptions(
            name='tipodocumento',
            options={'verbose_name': 'Tipo de Documento', 'verbose_name_plural': 'GRAL - Tipos de Documento'},
        ),
        migrations.AlterModelOptions(
            name='tipodomicilio',
            options={'verbose_name': 'Tipo de Domicilio', 'verbose_name_plural': 'GRAL - Tipos de Domicilio'},
        ),
        migrations.AlterModelOptions(
            name='tipofrecuencia',
            options={'verbose_name': 'Tipo de Frecuencia', 'verbose_name_plural': 'GRAL - Tipos de Frecuencia'},
        ),
        migrations.AlterModelOptions(
            name='tipoindice',
            options={'verbose_name': 'Tipo de Indice', 'verbose_name_plural': 'GRAL - Tipos de Indice'},
        ),
        migrations.AlterModelOptions(
            name='tiporesponsable',
            options={'verbose_name': 'Tipo de Responsable', 'verbose_name_plural': 'GRAL - Tipos de Responsable'},
        ),
        migrations.AlterModelOptions(
            name='tiposede',
            options={'verbose_name': 'Tipo de Sede', 'verbose_name_plural': 'GRAL - Tipos de Sede'},
        ),
        migrations.AlterModelOptions(
            name='tiposujeto',
            options={'verbose_name': 'Tipo de Sujeto', 'verbose_name_plural': 'IMPU - Tipos de Sujeto'},
        ),
        migrations.AlterModelOptions(
            name='tipovalor',
            options={'verbose_name': 'Tipo de Valor', 'verbose_name_plural': 'GRAL - Tipos de Valor'},
        ),
        migrations.AlterModelOptions(
            name='unidadmedida',
            options={'verbose_name': 'Unidad de Medida', 'verbose_name_plural': 'GRAL - Unidades de Medida'},
        ),
    ]
