# Generated by Django 5.1.1 on 2024-10-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0003_modulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='sigla',
            field=models.CharField(default='', max_length=10),
        ),
    ]
