# Generated by Django 5.1.1 on 2024-10-03 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0004_modulo_sigla'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codigopostal',
            old_name='sigla',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='pais',
            old_name='sigla',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='provincia',
            old_name='sigla',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='tipodocumento',
            old_name='sigla',
            new_name='codigo',
        ),
    ]
