# Generated by Django 5.1.1 on 2024-10-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0007_tiporesponsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiporesponsable',
            name='sigla',
            field=models.CharField(default='', max_length=10),
        ),
    ]
