# Generated by Django 5.1.1 on 2024-10-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0013_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneda',
            name='sigla',
            field=models.CharField(default='', max_length=10),
        ),
    ]
