# Generated by Django 5.1.1 on 2024-10-03 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0015_mascara'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipodocumento',
            name='mascara',
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='idmascara',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MasterModels.mascara'),
            preserve_default=False,
        ),
    ]
