# Generated by Django 5.1.1 on 2024-10-03 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0017_formadepago_formadepagodetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled', models.BooleanField(default=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=18)),
                ('vendedor', models.DecimalField(decimal_places=2, max_digits=18)),
                ('comprador', models.DecimalField(decimal_places=2, max_digits=18)),
                ('idmoneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.moneda')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.persona')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
