# Generated by Django 5.1.1 on 2024-10-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0018_tipodecambio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodecambio',
            name='fecha',
            field=models.DateField(),
        ),
    ]
