# Generated by Django 5.1.1 on 2024-10-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0019_alter_tipodecambio_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formadepago',
            name='codigo',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
