# Generated by Django 5.1.1 on 2024-10-03 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0020_alter_formadepago_codigo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tipodecambio',
            unique_together={('fecha', 'idmoneda')},
        ),
    ]
