# Generated by Django 5.1.1 on 2024-10-03 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0022_alter_codigopostal_codigo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codigopostal',
            options={'verbose_name': 'Codigo Postal', 'verbose_name_plural': 'Codigos Postales'},
        ),
        migrations.AlterModelOptions(
            name='conceptoincluido',
            options={'verbose_name': 'Concepto Incluido', 'verbose_name_plural': 'Conceptos Incluidos'},
        ),
        migrations.AlterModelOptions(
            name='formadepago',
            options={'verbose_name': 'Forma de Pago', 'verbose_name_plural': 'Formas de Pago'},
        ),
        migrations.AlterModelOptions(
            name='formadepagodetalle',
            options={'verbose_name': 'Forma de Pago - Detalle', 'verbose_name_plural': 'Formas de Pago - Detalle'},
        ),
        migrations.AlterModelOptions(
            name='idioma',
            options={'verbose_name': 'Idioma', 'verbose_name_plural': 'Idioma'},
        ),
        migrations.AlterModelOptions(
            name='incoterm',
            options={'verbose_name': 'Incoterm', 'verbose_name_plural': 'Incoterms'},
        ),
        migrations.AlterModelOptions(
            name='mascara',
            options={'verbose_name': 'Mascara', 'verbose_name_plural': 'Mascaras'},
        ),
        migrations.AlterModelOptions(
            name='modulo',
            options={'verbose_name': 'Modulo', 'verbose_name_plural': 'Modulos'},
        ),
        migrations.AlterModelOptions(
            name='moneda',
            options={'verbose_name': 'Moneda', 'verbose_name_plural': 'Monedas'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'Pais', 'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'verbose_name': 'Provincia', 'verbose_name_plural': 'Provincias'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='tipocomprobante',
            options={'verbose_name': 'Tipo de Comprobante', 'verbose_name_plural': 'Tipos de Comprobante'},
        ),
        migrations.AlterModelOptions(
            name='tipodecambio',
            options={'verbose_name': 'Tipo de Cambio', 'verbose_name_plural': 'Tipos de Cambio'},
        ),
        migrations.AlterModelOptions(
            name='tipodocumento',
            options={'verbose_name': 'Tipo de Documento', 'verbose_name_plural': 'Tipos de Documento'},
        ),
        migrations.AlterModelOptions(
            name='tiporesponsable',
            options={'verbose_name': 'Tipo de Responsable', 'verbose_name_plural': 'Tipos de Responsable'},
        ),
        migrations.AlterModelOptions(
            name='tiposujeto',
            options={'verbose_name': 'Tipo de Sujeto', 'verbose_name_plural': 'Tipos de Sujeto'},
        ),
        migrations.AlterModelOptions(
            name='unidadmedida',
            options={'verbose_name': 'Unidad de Medida', 'verbose_name_plural': 'Unidades de Medida'},
        ),
        migrations.CreateModel(
            name='PersonaRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled', models.BooleanField(default=False)),
                ('idpersona', models.CharField(max_length=255)),
                ('idrol', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.persona')),
            ],
            options={
                'verbose_name': 'Persona Roles',
                'verbose_name_plural': 'Personas Roles',
                'unique_together': {('idpersona', 'idrol')},
            },
        ),
    ]
