# Generated by Django 5.1.1 on 2024-10-03 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0023_alter_codigopostal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personarol',
            name='idpersona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='MasterModels.persona'),
        ),
        migrations.AlterField(
            model_name='personarol',
            name='idrol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.rol'),
        ),
    ]
