# Generated by Django 5.1.1 on 2024-10-03 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0024_alter_personarol_idpersona_alter_personarol_idrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuitPais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled', models.BooleanField(default=False)),
                ('cuit', models.CharField(max_length=10, unique=True)),
                ('idmascara', models.ForeignKey(default='80', on_delete=django.db.models.deletion.CASCADE, to='MasterModels.mascara')),
                ('idpais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.pais')),
                ('idtiposujeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.tiposujeto')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.persona')),
            ],
            options={
                'verbose_name': 'CUIT Pais',
                'verbose_name_plural': 'CUIT Paises',
                'unique_together': {('idpais', 'idtiposujeto')},
            },
        ),
    ]
