# Generated by Django 5.1.1 on 2024-10-03 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0026_alter_cuitpais_options_remove_pais_cuit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIndice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('idmoneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.moneda')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.persona')),
            ],
            options={
                'verbose_name': 'Tipo de Indice',
                'verbose_name_plural': 'Tipos de Indice',
                'unique_together': {('codigo',)},
            },
        ),
    ]
