# Generated by Django 5.1.1 on 2024-10-04 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0028_tipoajuste_plandecuentas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandecuentas',
            name='idpadre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterModels.plandecuentas'),
        ),
    ]
