# Generated by Django 5.1.1 on 2024-10-04 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0029_alter_plandecuentas_idpadre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandecuentas',
            name='idpadre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='MasterModels.plandecuentas'),
        ),
    ]
