# Generated by Django 5.1.1 on 2024-10-04 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0033_padronimpuesto_tipofrecuencia_tipovalor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipovalor',
            options={'verbose_name': 'Tipo de Valor', 'verbose_name_plural': 'Tipos de Valor'},
        ),
        migrations.CreateModel(
            name='Jurisdiccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(default='', max_length=10, unique=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.persona')),
            ],
            options={
                'verbose_name': 'Jurisdiccion',
                'verbose_name_plural': 'Jurisdicciones',
            },
        ),
        migrations.CreateModel(
            name='TipoCalculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(default='', max_length=10, unique=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.persona')),
            ],
            options={
                'verbose_name': 'Tipo de Calculo',
                'verbose_name_plural': 'Tipos de Calculo',
            },
        ),
    ]
