# Generated by Django 5.1.1 on 2024-10-04 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0034_alter_tipovalor_options_jurisdiccion_tipocalculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
                ('idtipoindice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.tipoindice')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.persona')),
            ],
            options={
                'verbose_name': 'Indice',
                'verbose_name_plural': 'Indices',
                'unique_together': {('codigo',)},
            },
        ),
    ]
