# Generated by Django 5.1.1 on 2024-10-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0035_indice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indice',
            unique_together={('idtipoindice', 'idtipoindice')},
        ),
        migrations.AddField(
            model_name='indice',
            name='importe',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.RemoveField(
            model_name='indice',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='indice',
            name='nombre',
        ),
    ]
