# Generated by Django 5.1.1 on 2024-10-04 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0037_tipoindice_idtipofrecuencia_tipoindice_idtipovalor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoindice',
            name='idtipovalor',
        ),
    ]
