# Generated by Django 5.1.1 on 2024-10-04 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0038_remove_tipoindice_idtipovalor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoindice',
            name='idtipovalor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MasterModels.tipovalor'),
            preserve_default=False,
        ),
    ]
