# Generated by Django 5.1.1 on 2024-10-04 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0039_tipoindice_idtipovalor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jurisdiccion',
        ),
    ]
