# Generated by Django 5.1.1 on 2024-10-04 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0041_clasificacionimpuesto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indice',
            unique_together={('idtipoindice',)},
        ),
        migrations.CreateModel(
            name='TipoImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(default='', max_length=10, unique=True)),
                ('idclasificacionimpuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.clasificacionimpuesto')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.persona')),
            ],
            options={
                'verbose_name': 'Tipo de Impuesto',
                'verbose_name_plural': 'Tipos de Impuesto',
                'unique_together': {('codigo',)},
            },
        ),
    ]
