# Generated by Django 5.1.1 on 2024-10-04 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0042_alter_indice_unique_together_tipoimpuesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('idprovincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.provincia')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.persona')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
            },
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(default='', max_length=10, unique=True)),
                ('calculapadron', models.BooleanField()),
                ('idalicuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.alicuotaimpuesto')),
                ('idpadron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.padronimpuesto')),
                ('idplandecuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.plandecuentas')),
                ('idprovincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.provincia')),
                ('idtipoimpuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.tipoimpuesto')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.persona')),
                ('idpartido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.partido')),
            ],
            options={
                'verbose_name': 'Tipo de Impuesto',
                'verbose_name_plural': 'Tipos de Impuesto',
                'unique_together': {('codigo',)},
            },
        ),
    ]
