# Generated by Django 5.1.1 on 2024-10-04 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0043_partido_impuesto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impuesto',
            options={'verbose_name': 'Impuesto', 'verbose_name_plural': 'Impuestos'},
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='idpadron',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterModels.padronimpuesto'),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='idpartido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterModels.partido'),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='idprovincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterModels.provincia'),
        ),
    ]
