# Generated by Django 5.1.1 on 2024-10-04 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0044_alter_impuesto_options_alter_impuesto_idpadron_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impuesto',
            name='idpadron',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterModels.padronimpuesto'),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='idpartido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterModels.partido'),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='idprovincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterModels.provincia'),
        ),
    ]
