# Generated by Django 5.1.1 on 2024-10-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0045_alter_impuesto_idpadron_alter_impuesto_idpartido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formadepago',
            name='habiles',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formadepagodetalle',
            name='cuota',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formadepagodetalle',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
