# Generated by Django 5.1.1 on 2024-10-06 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0046_formadepago_habiles_formadepagodetalle_cuota_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled', models.BooleanField(default=False)),
                ('nombrefantasia', models.CharField(max_length=256)),
                ('nombre', models.CharField(max_length=256)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('intercompany', models.BooleanField(default=False)),
                ('idtiporesponsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterModels.tiporesponsable')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.persona')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
                'unique_together': {('codigo',)},
            },
        ),
    ]
