# Generated by Django 5.1.1 on 2024-10-06 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0047_entidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alicuotaimpuesto',
            options={'verbose_name': 'Alicuota', 'verbose_name_plural': 'IMPU - Alicuotas Impuestos'},
        ),
        migrations.AlterModelOptions(
            name='clasificacionimpuesto',
            options={'verbose_name': 'Clasificacion Impuesto', 'verbose_name_plural': 'IMPU - Clasificaciones de Impuestos'},
        ),
        migrations.AlterModelOptions(
            name='codigopostal',
            options={'verbose_name': 'Codigo Postal', 'verbose_name_plural': 'GRAL - Codigos Postales'},
        ),
        migrations.AlterModelOptions(
            name='conceptoincluido',
            options={'verbose_name': 'Concepto Incluido', 'verbose_name_plural': 'IMPU -Conceptos Incluidos'},
        ),
        migrations.AlterModelOptions(
            name='cuitpais',
            options={'verbose_name': 'CUIT Pais', 'verbose_name_plural': 'IMPU - Paises CUIT'},
        ),
        migrations.AlterModelOptions(
            name='entidad',
            options={'verbose_name': 'Entidad', 'verbose_name_plural': 'ENTI - Entidades'},
        ),
        migrations.AlterModelOptions(
            name='formadepago',
            options={'verbose_name': 'Forma de Pago', 'verbose_name_plural': 'GRAL - Formas de Pago'},
        ),
        migrations.AlterModelOptions(
            name='formadepagodetalle',
            options={'verbose_name': 'Forma de Pago - Detalle', 'verbose_name_plural': 'GRAL - Formas de Pago - Detalle'},
        ),
        migrations.AlterModelOptions(
            name='idioma',
            options={'verbose_name': 'Idioma', 'verbose_name_plural': 'IMPU - Idioma'},
        ),
        migrations.AlterModelOptions(
            name='impuesto',
            options={'verbose_name': 'Impuesto', 'verbose_name_plural': 'IMPU - Impuestos'},
        ),
        migrations.AlterModelOptions(
            name='incoterm',
            options={'verbose_name': 'Incoterm', 'verbose_name_plural': 'IMPU -Incoterms'},
        ),
        migrations.AlterModelOptions(
            name='indice',
            options={'verbose_name': 'Indice', 'verbose_name_plural': 'IMPU - Indices'},
        ),
        migrations.AlterModelOptions(
            name='mascara',
            options={'verbose_name': 'Mascara', 'verbose_name_plural': 'GRAL - Mascaras'},
        ),
        migrations.AlterModelOptions(
            name='modulo',
            options={'verbose_name': 'Modulo', 'verbose_name_plural': 'GRAL - Modulos'},
        ),
        migrations.AlterModelOptions(
            name='moneda',
            options={'verbose_name': 'Moneda', 'verbose_name_plural': 'IMPU - Monedas'},
        ),
        migrations.AlterModelOptions(
            name='padronimpuesto',
            options={'verbose_name': 'Padron', 'verbose_name_plural': 'IMPU - Padrones Impuesto'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'Pais', 'verbose_name_plural': 'GRAL - Paises'},
        ),
        migrations.AlterModelOptions(
            name='partido',
            options={'verbose_name': 'Partido', 'verbose_name_plural': 'GRAL - Partidos'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'Persona', 'verbose_name_plural': 'GRAL - Personas'},
        ),
        migrations.AlterModelOptions(
            name='personarol',
            options={'verbose_name': 'Persona Roles', 'verbose_name_plural': 'GRAL - Personas Roles'},
        ),
        migrations.AlterModelOptions(
            name='plandecuentas',
            options={'verbose_name': 'Cuenta Contable', 'verbose_name_plural': 'CONT - Plan de Cuentas'},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'verbose_name': 'Provincia', 'verbose_name_plural': 'GRAL - Provincias'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'GRAL - Roles'},
        ),
        migrations.AlterModelOptions(
            name='tipoajuste',
            options={'verbose_name': 'Tipo de Ajuste', 'verbose_name_plural': 'CONT - Tipos de Ajuste Contable'},
        ),
        migrations.AlterModelOptions(
            name='tipocalculo',
            options={'verbose_name': 'Tipo de Calculo', 'verbose_name_plural': 'IMPU - Tipos de Calculo'},
        ),
        migrations.AlterModelOptions(
            name='tipocomprobante',
            options={'verbose_name': 'Tipo de Comprobante', 'verbose_name_plural': 'IMPU - Tipos de Comprobante'},
        ),
        migrations.AlterModelOptions(
            name='tipodecambio',
            options={'verbose_name': 'Tipo de Cambio', 'verbose_name_plural': 'GRAL - Tipos de Cambio'},
        ),
        migrations.AlterModelOptions(
            name='tipodocumento',
            options={'verbose_name': 'Tipo de Documento', 'verbose_name_plural': 'IMPU - Tipos de Documento'},
        ),
        migrations.AlterModelOptions(
            name='tipofrecuencia',
            options={'verbose_name': 'Tipo de Frecuencia', 'verbose_name_plural': 'IMPU - Tipos de Frecuencia'},
        ),
        migrations.AlterModelOptions(
            name='tipoimpuesto',
            options={'verbose_name': 'Tipo de Impuesto', 'verbose_name_plural': 'IMPU - Tipos de Impuesto'},
        ),
        migrations.AlterModelOptions(
            name='tipoindice',
            options={'verbose_name': 'Tipo de Indice', 'verbose_name_plural': 'IMPU - Tipos de Indice'},
        ),
        migrations.AlterModelOptions(
            name='tiporesponsable',
            options={'verbose_name': 'Tipo de Responsable', 'verbose_name_plural': 'IMPU -Tipos de Responsable'},
        ),
        migrations.AlterModelOptions(
            name='tiposujeto',
            options={'verbose_name': 'Tipo de Sujeto', 'verbose_name_plural': 'IMPU -Tipos de Sujeto'},
        ),
        migrations.AlterModelOptions(
            name='tipovalor',
            options={'verbose_name': 'Tipo de Valor', 'verbose_name_plural': 'IMPU - Tipos de Valor'},
        ),
        migrations.AlterModelOptions(
            name='unidadmedida',
            options={'verbose_name': 'Unidad de Medida', 'verbose_name_plural': 'IMPU - Unidades de Medida'},
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.persona')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'GRAL - Sectores',
            },
        ),
    ]
