# Generated by Django 5.1.1 on 2024-10-06 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0049_listaprecios_zona'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPrecioEntidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled', models.BooleanField(default=False)),
                ('identidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.entidad')),
                ('idlistaprecio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.listaprecios')),
                ('idmodulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.modulo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.persona')),
            ],
            options={
                'verbose_name': 'Listas de Precio',
                'verbose_name_plural': 'ENTI - Listas de Precio por Entidad',
                'unique_together': {('identidad', 'idmodulo', 'idlistaprecio')},
            },
        ),
    ]
