# Generated by Django 5.1.1 on 2024-10-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0050_listaprecioentidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaprecios',
            name='codigo',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
