# Generated by Django 5.1.1 on 2024-10-07 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0051_alter_listaprecios_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionCrediticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled', models.BooleanField(default=False)),
                ('vigenciadesde', models.DateField()),
                ('vigenciahasta', models.DateField()),
                ('limitedesde', models.DecimalField(decimal_places=2, max_digits=18)),
                ('limitehasta', models.DecimalField(decimal_places=2, max_digits=18)),
                ('identidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.entidad')),
                ('idmodulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.modulo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.persona')),
            ],
            options={
                'verbose_name': 'Condicion Crediticia',
                'verbose_name_plural': 'ENTI - Condiciones Crediticias',
            },
        ),
    ]
