# Generated by Django 5.1.1 on 2024-10-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0053_impuestoentidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impuestoentidad',
            name='porcentajexencion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='impuestoentidad',
            name='vigenciadesde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='impuestoentidad',
            name='vigenciahasta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
