# Generated by Django 5.1.1 on 2024-10-07 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0054_alter_impuestoentidad_porcentajexencion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejecutivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled', models.BooleanField(default=False)),
                ('identidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.entidad')),
                ('idpersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecutivos', to='MasterModels.persona')),
                ('idrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.rol')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.persona')),
            ],
            options={
                'verbose_name': 'Ejecutivo',
                'verbose_name_plural': 'ENTI - Ejecutivos',
                'unique_together': {('identidad', 'idpersona', 'idrol')},
            },
        ),
    ]
