# Generated by Django 5.1.1 on 2024-10-07 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0055_ejecutivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosFiscalesEntidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled', models.BooleanField(default=False)),
                ('numerodocumento', models.CharField(max_length=100)),
                ('identidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.entidad')),
                ('idtipodocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.tipodocumento')),
                ('idtiposujeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.rol')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.persona')),
            ],
            options={
                'verbose_name': 'Datos Fiscales',
                'verbose_name_plural': 'ENTI - Datos Fiscales por Entidad',
                'unique_together': {('identidad', 'idtipodocumento', 'numerodocumento')},
            },
        ),
    ]
