# Generated by Django 5.1.1 on 2024-10-07 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0056_datosfiscalesentidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosfiscalesentidad',
            name='idtiposujeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.tiposujeto'),
        ),
    ]
