# Generated by Django 5.1.1 on 2024-10-07 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0057_alter_datosfiscalesentidad_idtiposujeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoEntidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=200)),
                ('rol', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=200)),
                ('identidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.entidad')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.persona')),
            ],
            options={
                'verbose_name': 'Contacto Entidad',
                'verbose_name_plural': 'ENTI - Contactos Entidad',
                'unique_together': {('identidad', 'nombre')},
            },
        ),
    ]
