# Generated by Django 5.1.1 on 2024-10-07 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0059_tipodomicilio_tiposede'),
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionEntidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('calle', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=50)),
                ('piso', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
                ('diasentrega', models.CharField(max_length=200)),
                ('diasretiro', models.CharField(max_length=200)),
                ('idcodigopostal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.codigopostal')),
                ('identidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.entidad')),
                ('idpais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.pais')),
                ('idpartido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.partido')),
                ('idprovincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.provincia')),
                ('idtipodomicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.tipodomicilio')),
                ('idtiposede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.tiposede')),
                ('idzona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.zona')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.persona')),
            ],
            options={
                'verbose_name': 'Direccion Entidad',
                'verbose_name_plural': 'ENTI - Direcciones de Entidad',
                'unique_together': {('identidad', 'nombre')},
            },
        ),
    ]
