# Generated by Django 5.1.1 on 2024-10-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0060_direccionentidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona',
            name='codigo',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
