# Generated by Django 5.1.1 on 2024-10-07 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterModels', '0061_alter_zona_codigo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormaDePagoDetalle',
            new_name='FormaPagoDetalle',
        ),
        migrations.RenameModel(
            old_name='PlanDeCuentas',
            new_name='PlanCuentas',
        ),
        migrations.RenameField(
            model_name='formapagodetalle',
            old_name='idformadepago',
            new_name='idformapago',
        ),
        migrations.RenameField(
            model_name='impuesto',
            old_name='idplandecuenta',
            new_name='idplancuenta',
        ),
        migrations.RenameModel(
            old_name='FormaDePago',
            new_name='FormaPago',
        ),
        migrations.CreateModel(
            name='FormaPagoEntidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled', models.BooleanField(default=False)),
                ('identidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.entidad')),
                ('idformapago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.formapago')),
                ('idmodulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.modulo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.persona')),
            ],
            options={
                'verbose_name': 'Forma de Pago por Entidad',
                'verbose_name_plural': 'ENTI - Forma de Pago por Entidad',
                'unique_together': {('identidad', 'idmodulo', 'idformapago')},
            },
        ),
        migrations.CreateModel(
            name='ModuloEntidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled', models.BooleanField(default=False)),
                ('identidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.entidad')),
                ('idmodulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.modulo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.persona')),
            ],
            options={
                'verbose_name': 'Modulo por Entidad',
                'verbose_name_plural': 'ENTI - Modulos por Entidad',
                'unique_together': {('identidad', 'idmodulo')},
            },
        ),
        migrations.CreateModel(
            name='SectorEntidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled', models.BooleanField(default=False)),
                ('identidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.entidad')),
                ('idmodulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.modulo')),
                ('idsector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.sector')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterModels.persona')),
            ],
            options={
                'verbose_name': 'Sector por Entidad',
                'verbose_name_plural': 'ENTI - Sectores por Entidad',
                'unique_together': {('identidad', 'idmodulo', 'idsector')},
            },
        ),
    ]
