#Importa todos los modulos 
from .alicuotaimpuesto import AlicuotaImpuestoViewSet 
from .clasificacionimpuesto import ClasificacionImpuestoViewSet 
from .conceptoincluido import ConceptoIncluidoViewSet 
from .cuitpais import CuitPaisViewSet 
from .impuesto import ImpuestoViewSet 
from .padronimpuesto import PadronImpuestoViewSet 
from .tipocalculo import TipoCalculoViewSet 
from .tipocomprobante import TipoComprobanteViewSet 
from .tipoimpuesto import TipoImpuestoViewSet 
from .tiposujeto import TipoSujetoViewSet 
