# Importa todos los modulos
from MasterSerializers.serializers_producto.atributo import AtributoSerializer
from MasterSerializers.serializers_producto.atributoproducto import AtributoProductoSerializer
from MasterSerializers.serializers_producto.atributotipo import AtributoTipoSerializer
from MasterSerializers.serializers_producto.atributovalor import AtributoValorSerializer
from MasterSerializers.serializers_producto.claseproducto import ClaseProductoSerializer
from MasterSerializers.serializers_producto.contabilidadproducto import ContabilidadProductoSerializer
from MasterSerializers.serializers_producto.conversionproducto import ConversionProductoSerializer
from MasterSerializers.serializers_producto.listaprecios import ListaPrecioSerializer
from MasterSerializers.serializers_producto.listatipo import ListaTipoSerializer
from MasterSerializers.serializers_producto.precio import PrecioSerializer
from MasterSerializers.serializers_producto.tipoproducto import TipoProductoSerializer
from MasterSerializers.serializers_producto.producto import ProductoSerializer