# Importa todos los modulos 
from .codigopostal import CodigoPostal
from .formapago import FormaPago
from .formapagodetalle import FormaPagoDetalle
from .idioma import Idioma
from .incoterms import Incoterms
from .indice import Indice
from .mascara import Mascara
from .modulo import Modulo
from .moneda import Moneda
from .pais import Pais
from .partido import Partido
from .persona import Persona
from .personarol import PersonaRol
from .provincia import Provincia
from .rol import Rol
from .sector import Sector
from .tipocambio import TipoCambio
from .tipodocumento import TipoDocumento
from .tipodomicilio import TipoDomicilio
from .tipofrecuencia import TipoFrecuencia
from .tipoindice import TipoIndice
from .tiporesponsable import TipoResponsable
from .tiposede import TipoSede
from .tipovalor import TipoValor
from .unidadmedida import UnidadMedida